server:
  port: 9095
spring:
  jpa:
    #generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/reviewsratings
    username: postgres
    password: root
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

scheduler:
  batchSize: 100


feign:
  client:
    config:
      default:
        loggerLevel: full